### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/turnkey-curator-portal#104]
From @aimeehan1: Dates do not appear in iso8601date format. Only provide YYYYMMDD. Do not add additional time stamp data.

**Comment by JacqSauer** [comment]
Image reference: [JAS 2024-03-25, image 2](https://docs.google.com/document/d/1Wt2z2D37seaf6dxE4ySsnRzcYP7ozvW4TArHcCiDJRg/edit?usp=sharing)

**Comment by aimeehan1** [comment]
Thanks for referencing the screenshot file, @JacqSauer. This issue applied to downloaded data.
