### ISSUE TITLE
Verification status data not present in downloaded line list

### ISSUE THREAD

**Issue by sadiekelly** [globaldothealth/turnkey-curator-portal#109]
**Describe the bug**
The column caseReference.verificationStatus (verified/not verified) is present in the linelist download but contains no data. 

**To Reproduce**

**Expected behavior**
Verification status information might be useful for users to decide whether they wish to use data from unverified cases.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by jim-sheldon** [comment]
I don't see this in the `outbreak-schema` repo, `case-reference.ts`, or the database.

**Comment by jim-sheldon** [comment]
Our COVID export only included verified cases. Did we want to include unverified cases as well? If not, we can close this. If so, this will require a new field.

**Comment by aimeehan1** [comment]
Data exports should only include verified cases. This column would not be needed.

**Comment by jim-sheldon** [comment]
Fixed in #74
