### ISSUE TITLE
Consider removal of Date auto-populate function

### ISSUE THREAD

**Issue by aimeehan1** [globaldothealth/turnkey-curator-portal#115]
**Describe the bug**
When editing a case, dates are auto populating for date fields. Every time I go to edit a case, fields with dates are auto populating to today's date and I have to clear (manually delete) the data. If we forget to clear the data, then this information is applied and is wrong! 

The only field that we want to auto populate is the **Entry Date**. Should we consider removing the auto-populate function for other date fields?

**To Reproduce**
1. Go to Case ID63
2. Click on Edit
3. Scroll down to 'Confirmed case date' 'Onset of Symptoms Date' 'First clinical consultation date' 'Travel History' etc. All date fields! 
4. See error: You'll see that the system has auto-populated today's date. A curator has to delete this date before committing changes. 

**Expected behavior**
Dates should not auto-populate 

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

This is similar to an issue noted by Kelsey where dates would shift a day.

**Comment by jim-sheldon** [comment]
Possibly fixed by #73

**Comment by aimeehan1** [comment]
@jim-sheldon I just reproduced the error, so don't think it's corrected yet.
