### ISSUE TITLE
Export fields needs updating in `fields.txt`

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/turnkey-curator-portal#51]
The export field whitelist in https://github.com/globaldothealth/turnkey-curator-portal/blob/main/data-serving/scripts/export-data/fields.txt needs to be fixed to reflect the new day zero outbreak schema.

**Alternatives**

* Export all fields: This may make fields meant to be private unintentionally exported
* Use a blacklist instead of whitelist: This would be robust to added fields that we want to include but not against fields that we want to exclude, which would necessitate a deploy.

**Comment by stanislaw-zakrzewski** [comment]
Resolved in #74
