### ISSUE TITLE
list and turnkey-curator-portal share the same exporter

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/turnkey-curator-portal#52]
As `fields.txt` has changed (#51), this will cause issues if code is pushed to gh/list that touches the export-data directory.

Choices:

* Change COVID-19 exports to `covid19-country-exporter` and `covid19-full-exporter`
* Use pathogen specific exporters
* Create a generic exporter for all pathogens.

Thoughts @jim-sheldon @stanislaw-zakrzewski ?

**Comment by stanislaw-zakrzewski** [comment]
Adding resources in AWS ECR for turnkey solved this issue.
