### ISSUE TITLE
Indicate whether each source is a government

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/turnkey-curator-portal#92]
From @aimeehan1: Government source Y/N should be noted for each source

**Comment by stanislaw-zakrzewski** [comment]
@aimeehan1 Could You add information about where this problem occurs?

**Comment by aimeehan1** [comment]
@stanislaw-zakrzewski 

Government Source Y/N is added / captured for each source when entering data.
![Source1](https://github.com/globaldothealth/turnkey-curator-portal/assets/105008363/f5d69da9-18bb-46fd-b23c-bfaab0a0031f)

However, this information does not appear for each source when you review the case information.
![Source2](https://github.com/globaldothealth/turnkey-curator-portal/assets/105008363/3327af39-cc0d-430b-a21a-620c2d7c3bd2)

We also need to number each of our sources (Source 1, Source 2, Source 3, etc.), but this is captured in a different ticket. 'Data Source URL" would say 'Source 1'
